from datetime import date
from typing import Any, Protocol, runtime_checkable

from app.vendas.models import ImportBatch, ItemVenda, Pagamento, Pedido, Produto


@runtime_checkable
class VendasRepositoryProtocol(Protocol):
    def __init__(self, session: Any) -> None: ...

    def get_batch_by_data(self, data_referencia: date) -> ImportBatch | None: ...

    def delete_batch_data(self, batch_id: int) -> None: ...

    def create_batch(self, batch: ImportBatch) -> ImportBatch: ...

    def bulk_insert_pedidos(self, pedidos: list[Pedido]) -> None: ...

    def bulk_insert_pagamentos(self, pagamentos: list[Pagamento]) -> None: ...

    def bulk_insert_itens(self, itens: list[ItemVenda]) -> None: ...

    def upsert_produtos(self, produtos: list[Produto]) -> None: ...

    def list_batches(self) -> list[ImportBatch]: ...
