from typing import Any, Protocol, runtime_checkable

from app.auth.models import User


@runtime_checkable
class UserRepositoryProtocol(Protocol):
    def __init__(self, session: Any) -> None: ...

    def get_by_id(self, user_id: int) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def list_all(self) -> list[User]: ...

    def create(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...

    def delete(self, user: User) -> None: ...
